---
scenario:
  create_sequence:
    # - dependency
    - create
    - prepare
  check_sequence:
    # - dependency
    # - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    # - dependency
    - create
    - prepare
    - converge
    - idempotence
  destroy_sequence:
    # - dependency
    # - cleanup
    - destroy
  test_sequence:
    # - dependency
    - lint
    # - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    - cleanup
    - destroy
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7-systemd
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos8-systemd
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu
    image: ubuntu:18.04
provisioner:
  log: true
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATHS: '../../../../../'
verifier:
  name: ansible
