---
# defaults file for ztp-setup
# Configure default connection parameter.
ansible_connection: paramiko

ansible_python_interpreter: $(which python)

# Method to become root
ansible_become_method: sudo

# Default password to become root
ansible_become_password: '{{ansible_password}}'

# List of packages to install to enable DHCP package
dhcp_packages:
  - dhcp

# State of the package
dhcp_packages_state: "present"

# DHCP configuration folder
dhcp_config_dir: /etc/dhcp

# Configuration File for DHCP service
dhcp_config: '{{ dhcp_config_dir }}/dhcpd.conf'

# DHCP service name
dhcp_service: dhcpd