name: Ansible Molecule
on:
  push:
  pull_request:
    paths:
      - 'ansible_collections/arista/cvp/roles/**'
      - 'ansible_collections/arista/cvp/molecules/**'
      - 'requirements.txt'
jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        avd_scenario:
          - dhcp_management_mac
          - dhcp_system_mac
    steps:
      - name: 'set environment variables'
        run: |
          echo "PY_COLORS=1" >> $GITHUB_ENV
          echo "ANSIBLE_FORCE_COLOR=1" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run molecule action
        uses: inetsix/molecule-collection-actions@master
        with:
          molecule_parentdir: 'ansible_collections/arista/cvp'
          molecule_command: 'test'
          molecule_args: '-s ${{ matrix.avd_scenario }}'
          pip_file: 'requirements.txt'
